[package]
name = "gvm"
version = "0.1.0"
edition = "2021"

[dependencies]
broom = "0.3.2"
logos = "0.14.2"
clap = { version = "4.5.21", features = ["derive"] }
thiserror = "2.0.3"
ariadne = "0.5.0"

[lib]
name = "gvm"
path = "src/lib.rs"

[[bin]]
name = "gvm"
path = "src/main.rs"
