name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      - name: Install Target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }}
